#*****************************************************************************
#  * Copyright (c) 2022 Intecs.
#  *
#  *    
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the Eclipse Public License v2.0
#  * which accompanies this distribution, and is available at
#  * http://www.eclipse.org/legal/epl-v20.html
#  *
#  * Contributors:
#  *  Felicien Ihirwe
#  *
#  *****************************************************************************/

version: "1"
services:
  Broker1:
    image: eclipse-mosquitto
    hostname: Environment1
    container_name: Broker1
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./conf:/mosquitto/conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - Broker1_net



  # LogicalService1:
  #     image: LogicalService1
  #     hostname: Environment1
  #     ports:
  #     volumes:
  # StreamingService1:
  #     image: StreamingService1
  #     hostname: Environment1
  #     ports:
  #     volumes:


networks:
  Broker1_net:
    driver: bridge
  LogicalService1_net:
    driver: bridge
  StreamingService1_net:
    driver: bridge
  EndUserApplication1_net:
    driver: bridge

