#*****************************************************************************
#  * Copyright (c) 2022 Intecs.
#  *
#  *    
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the Eclipse Public License v2.0
#  * which accompanies this distribution, and is available at
#  * http://www.eclipse.org/legal/epl-v20.html
#  *
#  * Contributors:
#  *  Felicien Ihirwe
#  *
#  *****************************************************************************/

version: "3.9"
services:
  MosquittoBroker:
    image: eclipse-mosquitto
    hostname: FogNode1
    container_name: MosquittoBroker
    ports:
      - 1883:1883 /tcp
    volumes:
      - ./conf:/mosquitto/conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - MosquittoBroker_net

networks:
  MosquittoBroker_net:
    driver: bridge
